services:
  backend:
    image: pankajmaulekhi/gdg_backend
    environment:
      - HUGGINGFACEHUB_API_TOKEN=""
    ports: 
     - '8000:8000'

  frontend:
    image: pankaj_maulekhi/gdg_frontend
    ports: 
     - '8501:8501'